import { Inter } from "next/font/google";
import "./globals.css";
import LeftSideBar from "./Components/LeftSideBar";
import TopNavBar from "./Components/TopNavBar";
import Settings from "./Components/Settings";
import AllDuaTitle from "./Components/AllDuaTitle";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#ebeef2] relative`}>
        <LeftSideBar />
        <TopNavBar />
        <Settings />
        {children}
        <AllDuaTitle />
      </body>
    </html>
  );
}
